Ds/2.3
ebbba-org/ansible-role-bigbluebutton pull request #108
Opened 2021-05-07 12:14 UTC by Davka

adds the ability to store recordings with scalelite on nfs-share

2021-05-07 12:39 UTC, BrutalBirdie requested changes
First of all, thanks for the PR!
I added some of my thoughts.

The whole recording and scalelite part is total alien to me since I never use BBB recordings, but would be happy about a session showing this in action.

2021-05-27 15:42 UTC, Davka reviewed
i think i have done all the change requests

2021-05-27 15:43 UTC, Davka commented on tasks/installation.yml
> +  when: not bbb_disable_recordings | bool
Done

2021-06-10 13:51 UTC, Davka commented on tasks/main.yml
> +
Done

2021-06-14 14:43 UTC, crosscodr commented
Hi @Davka, this PR needs to be rebased on current HEAD to get rid of ansible-lint-errors and to resolve conflicts.

2021-11-02 12:09 UTC, closed without merging