extend monitoring
ebbba-org/ansible-role-bigbluebutton pull request #111
Opened 2021-05-11 12:35 UTC by Davka

2021-05-26 13:48 UTC, n0emis commented on README.md
> +| `bbb_monitoring_ips` | a list of ip addresses for restricting access | `[]` | in array with key `server` |
```suggestion
| `bbb_monitoring_ips` | a list of ip addresses for restricting access | `[]` | in array with key `address` |
```

2021-05-27 18:19 UTC, BrutalBirdie approved these changes

2021-06-03 16:46 UTC, crosscodr requested changes

2021-06-03 16:46 UTC, crosscodr commented on templates/monitoring/monitoring.nginx.j2
> +  {% else %}
I personally wouldn't mind to have both ip restrictions and htpasswd in place.

2021-06-03 16:46 UTC, crosscodr commented on templates/monitoring/monitoring.nginx.j2
> +  {% endif %}
```suggestion
    {% endif %}
    auth_basic "BigBlueButton Exporter";
    auth_basic_user_file /etc/bigbluebutton/nginx/.htpasswd;
```

2021-06-03 16:46 UTC, crosscodr commented on templates/monitoring/monitoring.nginx.j2
> +  {% endif %}
```suggestion
    {% endif %}
    auth_basic "BigBlueButton Exporter";
    auth_basic_user_file /etc/bigbluebutton/nginx/.htpasswd;

```

2021-06-03 16:46 UTC, crosscodr commented on tasks/checkvars.yml
> +      when: bbb_monitoring_all_in_one_external and not bbb_monitoring_use_nginx_access_module | bool
see my comment to montoring.nginx.j2

2021-06-03 16:46 UTC, crosscodr commented on tasks/main.yml
> +  when: (bbb_monitoring_all_in_one_enable | bool) or (bbb_monitoring_all_in_one_external | bool)
I don't understand why do you need this here?

2021-06-09 14:36 UTC, Davka commented on tasks/checkvars.yml
> +      when: bbb_monitoring_all_in_one_external and not bbb_monitoring_use_nginx_access_module | bool
I changed it

2021-06-15 15:48 UTC, crosscodr commented
Sorry @Davka, this PR has to be reworked again.
There are a few simplifications made in #134, e.g. unified variable names.
Please merge and update this PR.

2021-07-07 08:19 UTC, Davka commented
Will submit a new PR

2021-07-07 08:19 UTC, closed without merging