greenlight: allow for provider-type in user:create
ebbba-org/ansible-role-bigbluebutton pull request #139
Opened 2021-05-31 15:08 UTC by einhirn

Fixes #135 - although I'm not sure if it's actually useful, because it still waits for changes in Greenlight...

2021-06-01 08:24 UTC, Davka approved these changes

2021-06-04 13:39 UTC, n0emis requested changes
This PR looks good so far, although some documentation of this feature in the README.md would be preferable...

2021-06-07 17:34 UTC, BrutalBirdie requested changes
README still missing

2021-06-12 10:19 UTC, einhirn commented
As "README.md" says see `defaults/main.yml` for details, I've added some explanation there.

This can be merged, but might not work as expected yet. There needs to be another PR once Greenlight accepts a PR TBD for updating `rake user:add` etc. It currently misses the ability to specify the "social_id" like "uid=X,ou=Y,dc=Z" for LDAP or whatever else for other auth plugins.

2021-09-16 14:10 UTC, crosscodr commented
Hi @einhirn, this looks good, but was this implemented in greenlight yet?

2021-09-16 15:22 UTC, einhirn commented
Hmm... Too long ago - I think this works only partially, because Ahmad Farhat of Greenlight just said something along the lines "rake:user was only ever meant to create local accounts". https://github.com/bigbluebutton/greenlight/issues/2742

Now it comes back to me: The new field "social_id" can't be set currently, so I can't add an ldap user as admin like i wanted...

I guess I'll create a PR for Greenlight in about 3 weeks from now... Didn't get around to do that yet.

2021-11-04 17:21 UTC, crosscodr commented
On my greenlight 2.9.2 instance rake -T shows
`rake user:create[name,email,password,role,provider]  # Creates a user account`
So I think this PR would work now.

2021-11-04 17:22 UTC, crosscodr approved these changes

2021-11-04 18:26 UTC, crosscodr requested changes

2021-11-04 18:26 UTC, crosscodr commented on tasks/greenlight.yml
> +      command: "docker exec greenlight-v2 bundle exec rake user:create[\"{{ item.name }}\",\"{{ item.email }}\",\"{{ item.password }}\",\"{{ item.type }}{{ ',' + item.provider if 'provider' in item.k
```suggestion
      command: "docker exec greenlight-v2 bundle exec rake user:create[\"{{ item.name }}\",\"{{ item.email }}\",\"{{ item.password }}\",\"{{ item.type }}\"{{ ',' + '"' + item.provider + '"' if 'provider' in item.keys() else '' }}]"
```

2021-11-05 04:34 UTC, Davka approved these changes

2021-11-05 07:29 UTC, einhirn commented
> 
> 
> On my greenlight 2.9.2 instance rake -T shows `rake user:create[name,email,password,role,provider] # Creates a user account` So I think this PR would work now.

No, "social_id" is still missing, and I didn't get around to prepare a PR against Greenlight yet... Maybe just close this PR? I don't know when I'll be able to get to it - also when a new PR would be merged to Greenlight upstream.

2021-11-05 08:07 UTC, crosscodr commented
> > On my greenlight 2.9.2 instance rake -T shows `rake user:create[name,email,password,role,provider] # Creates a user account` So I think this PR would work now.
> 
> No, "social_id" is still missing, and I didn't get around to prepare a PR against Greenlight yet... Maybe just close this PR? I don't know when I'll be able to get to it - also when a new PR would be merged to Greenlight upstream.

Yeah, thats right :(
I think we can still leave this PR as it is, in case this gets into greenlight some times.

2021-11-29 11:13 UTC, BrutalBirdie commented
Check the Ansible Lint and fix please.
Closed for now due to inactivity.
Send a message to reopen this PR.

2021-11-29 11:13 UTC, closed without merging