add backend for html5-client according to https://docs.bigbluebutton.…
ebbba-org/ansible-role-bigbluebutton pull request #149
Opened 2021-06-03 10:27 UTC by einhirn

add backend for html5-client according to https://docs.bigbluebutton.org/2.2/customize.html#collect-feedback-from-the-users

With this, people can add 
```yaml
bbb_meteor:
  public:
    clientLog:
      external:
        enabled: true
        url: "https://{{ bbb_hostname }}/html5log"
```
to their config and the logs get written to `/var/log/nginx/html5-client.log`

When switching the variable "bbb_client_log_enable" to "false", the changes are reverted - only the log file is left.

2021-06-03 13:53 UTC, BrutalBirdie commented
Please be sure ansible-lint does not produce any errors.
This might solved by merging the latest changes from the `bbb/2.3` branch.

2021-06-03 18:48 UTC, crosscodr reviewed
Looks good to me, but I don't see this part of the doc:
```
yq w -i $HTML5_CONFIG public.clientLog.external.enabled true
yq w -i $HTML5_CONFIG public.clientLog.external.url     "$PROTOCOL://$HOST/html5log"
yq w -i $HTML5_CONFIG public.app.askForFeedbackOnLogout true
```

A comment in README.md would be nice, too :)

2021-06-03 19:42 UTC, einhirn commented
> Looks good to me, but I don't see this part of the doc:

yes, I only mentioned it here in the original comment, which I just updated with the last line: https://github.com/ebbba-org/ansible-role-bigbluebutton/pull/149#issue-660787738

> A comment in README.md would be nice, too :)

Oh, of course, I'll whip something up...

2021-06-03 20:12 UTC, crosscodr commented
> > Looks good to me, but I don't see this part of the doc:
> 
> yes, I only mentioned it here in the original comment, which I just updated with the last line: [#149 (comment)](https://github.com/ebbba-org/ansible-role-bigbluebutton/pull/149#issue-660787738)
Oh yes, I overlooked that afterwards.
Thanks for the README-Entry

2021-06-03 20:23 UTC, BrutalBirdie commented
Instead of using `files/` I would suggest using template.
This way later on down the road these files can be templated if needed.

---
After reading the code again . . . 🤔
Since you do `copy` and `remove` based on `bbb_client_log_enable` template might not be the right option here... or?

Suggestion.
Yes use templates and only on the `remove` steps use [file](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html):
```yaml
- name: Remove file (delete file)
  ansible.builtin.file:
    path: /etc/foo.txt
    state: absent
```
This way the templates will be created based on `bbb_client_log_enable` and deleted.
Your thoughts?

2021-06-03 20:27 UTC, crosscodr commented
> Instead of using `files/` I would suggest using template.
> This way later on down the road these files can be templated if needed.

> Your thoughts?

Hi @BrutalBirdie, I would say, if it is needed to template a file, one could change the copy task to a template task and move from files to templates. Just my two cents :)

2021-06-03 20:28 UTC, einhirn commented
Template parsing takes time, so why do it if there aren't any variables in the file?
@crosscodr - exactly.

2021-06-03 20:43 UTC, BrutalBirdie approved these changes

2021-06-03 20:43 UTC, BrutalBirdie commented
NOTE:
I did not test this yet, reminder to myself do that :D

2021-06-03 20:54 UTC, Davka approved these changes

2021-06-04 07:00 UTC, crosscodr requested changes

2021-06-04 07:00 UTC, crosscodr commented on README.md
```suggestion
#### User Feedback logging
```

2021-06-04 08:33 UTC, crosscodr approved these changes

2021-06-04 08:52 UTC, merged