sip: play_and_get_digits moved to the defaults to make it configurable
ebbba-org/ansible-role-bigbluebutton pull request #158
Opened 2021-06-07 10:59 UTC by Davka

2021-06-07 14:43 UTC, crosscodr approved these changes

2021-06-07 17:33 UTC, BrutalBirdie requested changes
@Davka and I talked about this PR.
Adding a README entry is missing and a good explanation what these numbers do.

2021-06-08 08:59 UTC, crosscodr approved these changes

2021-06-09 16:44 UTC, BrutalBirdie approved these changes

2021-06-09 17:11 UTC, crosscodr approved these changes

2021-06-10 05:05 UTC, merged