Handle install/uninstall coturn
ebbba-org/ansible-role-bigbluebutton pull request #167
Opened 2021-06-09 10:26 UTC by ChrisKar96

Fixes #82 

If `bbb_coturn_enable` is set to false, coturn will be uninstalled and its configuration files removed.

I created a file to be copied at `/etc/default/coturn`, because uninstalling and reinstalling coturn was not creating the file again, so `lineinfile` was failing.

2021-06-09 14:34 UTC, crosscodr requested changes

2021-06-09 14:34 UTC, crosscodr commented on tasks/coturn.yml
> +    state: "{% if bbb_coturn_enable | bool %}present{% else %}absent{% endif %}"
```suggestion
    state: "{{ 'present' if bbb_coturn_enable | bool  else 'absent' }}"
```

2021-06-09 14:34 UTC, crosscodr commented on tasks/coturn.yml
> +    state: "{% if bbb_coturn_enable | bool %}started{% else %}stopped{% endif %}"
```suggestion
    state: "{{ 'started' if bbb_coturn_enable | bool else 'stopped' }}"
```

2021-06-14 15:25 UTC, crosscodr approved these changes

2021-06-14 17:44 UTC, crosscodr approved these changes

2021-06-15 08:08 UTC, Davka approved these changes

2021-06-15 08:08 UTC, merged