improve ansible tagging
ebbba-org/ansible-role-bigbluebutton pull request #188
Opened 2021-06-15 17:30 UTC by crosscodr

Improves and adds some additional tags.
Fixes use of `greenlight` and `monitoring` tags, by adding the tags to the depended docker tasks.
Also fixes #181.

2021-06-15 19:46 UTC, einhirn requested changes
An additional tag "geerlingguy" for both roles would reduce command line length when I want to skip both dependencies in one go.

2021-06-15 19:46 UTC, einhirn commented on meta/main.yml
> +    tags: geerlingguy_nodejs
An additional tag `geerlingguy` would help shorten the commandline when I want to skip both dependencies.

2021-07-07 08:21 UTC, Davka approved these changes

2021-08-04 09:58 UTC, crosscodr commented
Hi @BrutalBirdie, I resolved the merge conflicts. What do you think?

2021-08-19 18:36 UTC, BrutalBirdie approved these changes

2021-08-19 18:36 UTC, merged