Feature request: Extended bbb_dialin_default_play_and_get_digits
ebbba-org/ansible-role-bigbluebutton pull request #212
Opened 2021-07-02 18:10 UTC by wilkis3

This feature request will allow to use customize dailin announces.

e.g. `5 5 3 7000 # ivr/ivr-please_enter_pin_followed_by_pound.wav ivr/ivr-that_was_an_invalid_entry.wav pin \d+` to acconce to use the pound sign

2021-07-07 08:11 UTC, Davka approved these changes

2021-07-22 11:54 UTC, crosscodr requested changes

2021-07-22 11:54 UTC, crosscodr commented on defaults/main.yml
> +bbb_dialin_default_play_and_get_digits: "5 5 3 7000 # conference/conf-pin.wav ivr/ivr-that_was_an_invalid_entry.wav pin \\d+"
Hi @wilkis3, is the double-backslash here needed for escaping? If so, i would suggest to put this in readme as well.

2021-09-15 12:56 UTC, wilkis3 commented
Oh, I mixed up. Again.

2021-09-15 12:56 UTC, closed without merging