wait until rake did all necessary migrations before greenlight user creation
ebbba-org/ansible-role-bigbluebutton pull request #262
Opened 2021-11-03 10:21 UTC by olwe0002

the root cause of not created users is, like mentioned [here](https://github.com/ebbba-org/ansible-role-bigbluebutton/pull/260), that rake did not create all tables yet when the user is created.

so this MR waits until rake is done, then the user creation works fine.

2021-11-03 19:04 UTC, crosscodr requested changes
Hi @olwe0002, thank you for submitting this PR.
I have a suggestion for this task, how about using this module instead of command:
https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_exec_module.html

2021-11-04 01:58 UTC, olwe0002 commented
ok, I did that with my new change. I also changed "Create greenlight users" to the same module and improved the changed_when condition. please review

2021-11-04 13:27 UTC, crosscodr commented
Nice, looks good to me! Did you test this against a clean setup?

2021-11-04 19:11 UTC, crosscodr requested changes

2021-11-04 19:11 UTC, crosscodr commented on tasks/greenlight.yml
As a normal command, this can not be run in check mode and fails if not explicitly 
```suggestion
      when: not ansible_check_mode

```

2021-11-04 19:19 UTC, crosscodr requested changes

2021-11-04 19:19 UTC, crosscodr commented on tasks/greenlight.yml
> +
As a normal command, this can not be run in check mode and fails if not explicitly 
```suggestion
      when: not ansible_check_mode

```

2021-11-05 07:08 UTC, olwe0002 commented
yes, i did test it against a clean setup and it works. also I accepted your proposed change and squashed them into one single commit.

2021-11-05 08:03 UTC, crosscodr approved these changes

2021-11-07 00:09 UTC, BrutalBirdie approved these changes

2021-11-07 00:09 UTC, merged