@Wilkis3 selectable bbb version - PR214 repred
ebbba-org/ansible-role-bigbluebutton pull request #266
Opened 2021-11-19 14:18 UTC by BrutalBirdie

@wilkis3 said in #214
>Fixed #200 
>
>Some product like [fairblue](https://git.fairkom.net/chat/fairblue) works **not** for the newest BigBlueButton release anytimes.
>
>The copy task is needed to overwrite content. (see [ansible Issue #58386](https://github.com/ansible/ansible/issues/58386#issuecomment-505888418))

2021-11-19 14:24 UTC, BrutalBirdie commented
This PR also enables the option to change to a dev branch.
Example testing `2.4-rc-4` with mediasoup enabled:

```yaml
bbb_version: "bionic-240-2.4-rc-4"
```

and

```yaml
bbb_webrtc_sfu_multikurento:
  balancing-strategy: MEDIA_TYPE
  videoMediaServer: mediasoup
  screenshareMediaServer: mediasoup
  audioMediaServer: mediasoup
  kurento:
    - ip: "{{ ansible_default_ipv4.address }}"
      url: ws://127.0.0.1:8888/kurento
      mediaType: main
      ipClassMappings:
        local: ""
        private: ""
        public: ""
      options:
        failAfter: 5
        request_timeout: 30000
        response_timeout: 30000
    - ip: "{{ ansible_default_ipv4.address }}"
      url: ws://127.0.0.1:8889/kurento
      mediaType: audio
      ipClassMappings:
        local: ""
        private: ""
        public: ""
      options:
        failAfter: 5
        request_timeout: 30000
        response_timeout: 30000
    - ip: "{{ ansible_default_ipv4.address }}"
      url: ws://127.0.0.1:8890/kurento
      mediaType: content
      ipClassMappings:
        local: ""
        private: ""
        public: ""
      options:
        failAfter: 5
        request_timeout: 30000
        response_timeout: 30000
  freeswitch:
    sip_ip: "{{ ansible_default_ipv4.address }}"
    ip: "{{ ansible_default_ipv4.address }}"
    esl_password: "{{ bbb_freeswitch_socket_password }}"
  log:
    level: warn
    filename:
```

2021-11-19 14:36 UTC, crosscodr requested changes

2021-11-19 14:36 UTC, crosscodr commented on README.md
> +| `bbb_version` | Install specified BigBlueButton version | `bionic-230` | For installing specified BigBlueButton version e.g. `2.3.1` |
```suggestion
| `bbb_version` | Install specified BigBlueButton version | `bionic-230` | For installing specified BigBlueButton version e.g. `bionic-230-2.3.15` |
```

2021-11-19 14:36 UTC, crosscodr commented on tasks/repositories.yml
> +
Hi @BrutalBirdie,
you should add a cleanup-task for the old sources-list file:
`/etc/apt/sources.list.d/ubuntu_bigbluebutton_org_bionic_230.list`.
```suggestion

- name: remove deprecated bigbluebutton sources-list file
  file:
    path: '/etc/apt/sources.list.d/ubuntu_bigbluebutton_org_bionic_230.list'
    state: absent

```
Btw. which sources-list file would bbb-install.sh create?

2021-11-19 14:46 UTC, crosscodr commented on tasks/repositories.yml
> +    state: absent
```suggestion
- name: remove deprecated bigbluebutton sources-list file
  become: true
  ansible.builtin.file:
    path: '/etc/apt/sources.list.d/ubuntu_bigbluebutton_org_bionic_230.list'
    state: absent
```

2021-11-19 14:49 UTC, crosscodr commented
Hi @BrutalBirdie, I think it would be cleaner, if you rebase this PR and squash the intermediate commits. What do you think?

2021-11-22 08:24 UTC, crosscodr approved these changes

2021-11-22 08:44 UTC, wilkis3 approved these changes
Sorry, I forgot the Pull request. I can approve your changes.

2021-11-22 14:58 UTC, Davka approved these changes

2021-11-22 14:58 UTC, merged